import { ROLES, RoleType } from './roles';

export const PERMISSIONS = {
  // Dashboard
  DASHBOARD_PROGRESS: 'DASHBOARD_PROGRESS',
  DASHBOARD_CAPACITY: 'DASHBOARD_CAPACITY',
  
  // Report
  REPORT_VIEW_GANTT: 'REPORT_VIEW_GANTT',
  REPORT_VIEW_HISTORY: 'REPORT_VIEW_HISTORY',
  REPORT_EXPORT: 'REPORT_EXPORT',
  
  // Project
  PRJ_VIEW: 'PRJ_VIEW',
  PRJ_CREATE: 'PRJ_CREATE',
  PRJ_UPDATE: 'PRJ_UPDATE',
  PRJ_DELETE: 'PRJ_DELETE',
  
  // Stage
  STAGE_VIEW: 'STAGE_VIEW',
  STAGE_CREATE: 'STAGE_CREATE',
  STAGE_UPDATE: 'STAGE_UPDATE',
  STAGE_DELETE: 'STAGE_DELETE',
  
  // Planning
  PLAN_VIEW_ALL: 'PLAN_VIEW_ALL',
  PLAN_VIEW_MACHINE: 'PLAN_VIEW_MACHINE',
  PLAN_UPDATE: 'PLAN_UPDATE',
  PLAN_AUTO: 'PLAN_AUTO',
  PLAN_SAVE: 'PLAN_SAVE',
  
  // Activity log
  LOG_VIEW: 'LOG_VIEW',
  
  // Machine
  MACHINE_VIEW: 'MACHINE_VIEW',
  MACHINE_MANAGE: 'MACHINE_MANAGE',
  
  // Mold template
  TEMPLATE_VIEW: 'TEMPLATE_VIEW',
  TEMPLATE_MANAGE: 'TEMPLATE_MANAGE',
  
  // User Admin
  USER_VIEW: 'USER_VIEW',
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  
  // Role & Permission Admin
  ROLE_VIEW: 'ROLE_VIEW',
  ROLE_MANAGE: 'ROLE_MANAGE',
  PERMISSION_VIEW: 'PERMISSION_VIEW',
  PERMISSION_MANAGE: 'PERMISSION_MANAGE',
  
  // Company Admin
  COMPANY_VIEW: 'COMPANY_VIEW',
  COMPANY_MANAGE: 'COMPANY_MANAGE',
  
  // System settings
  SYSTEM_SETTINGS: 'SYSTEM_SETTINGS'
} as const;

export type PermissionType = typeof PERMISSIONS[keyof typeof PERMISSIONS];

// Mapping permissions to roles
export const ROLE_PERMISSIONS: Record<RoleType, PermissionType[]> = {
  [ROLES.DIRECTOR]: [
    PERMISSIONS.DASHBOARD_PROGRESS,
    PERMISSIONS.DASHBOARD_CAPACITY,
    PERMISSIONS.REPORT_VIEW_GANTT,
    PERMISSIONS.REPORT_VIEW_HISTORY,
    PERMISSIONS.REPORT_EXPORT
  ],
  
  [ROLES.PROD_MANAGER]: [
    PERMISSIONS.DASHBOARD_PROGRESS,
    PERMISSIONS.PRJ_VIEW,
    PERMISSIONS.PRJ_CREATE,
    PERMISSIONS.PRJ_UPDATE,
    PERMISSIONS.PRJ_DELETE,
    PERMISSIONS.STAGE_VIEW,
    PERMISSIONS.STAGE_CREATE,
    PERMISSIONS.STAGE_UPDATE,
    PERMISSIONS.STAGE_DELETE,
    PERMISSIONS.PLAN_VIEW_ALL,
    PERMISSIONS.PLAN_UPDATE,
    PERMISSIONS.PLAN_AUTO,
    PERMISSIONS.PLAN_SAVE,
    PERMISSIONS.LOG_VIEW,
    PERMISSIONS.MACHINE_VIEW,
    PERMISSIONS.TEMPLATE_VIEW
  ],
  
  [ROLES.SHOP_OPERATOR]: [
    PERMISSIONS.PLAN_VIEW_MACHINE,
    PERMISSIONS.LOG_VIEW
  ],
  
  [ROLES.IT_ADMIN]: [
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_DELETE,
    PERMISSIONS.ROLE_VIEW,
    PERMISSIONS.ROLE_MANAGE,
    PERMISSIONS.PERMISSION_VIEW,
    PERMISSIONS.PERMISSION_MANAGE,
    PERMISSIONS.COMPANY_VIEW,
    PERMISSIONS.COMPANY_MANAGE,
    PERMISSIONS.MACHINE_VIEW,
    PERMISSIONS.MACHINE_MANAGE,
    PERMISSIONS.TEMPLATE_VIEW,
    PERMISSIONS.TEMPLATE_MANAGE
  ],
  
  [ROLES.SUPERADMIN]: Object.values(PERMISSIONS) as PermissionType[]
};
